### ISSUE TITLE
Дизайн и структура

### ISSUE THREAD

**Issue by NyashMyash99** [NyashStorage/coderock-2024-frontend-training#1]
Обсуждение проводим в беседе, в комментарии к задаче прикрепляем выбранный вариант с аргументацией, почему это решение показалось самым лучшим.

Если что-то забыл - упомяните в беседе, добавлю.

### Цвета
- [x] Задний фон.
- [x] Акцентный цвет.
- [x] Текст.
- [x] Текст поверх акцентного цвета.

### Вид базовых компонентов
- [x] Используемый шрифт.
- [x] Поля ввода.
> Например, с обводкой и закруглёнными краями или только с нижним подчёркиванием, как меняем при наведении и т.п.
- [x] Кнопки.
> Например, заполнены акцентным цветом или внутри пустые, но с обводкой и т.п.
- [x] Чек-боксы, если будут использоваться.
> Думаю здесь уже понятно, стандартный вид, при наведении, когда выбран и т.п.
- [x] Скролл-бар.

### Регистрация и авторизация
- [x] Модальное окно или отдельная страница? 
- [x] Какие элементы будут использоваться? ( например, ввод логина, ввод пароля, кнопка авторизации )
- [x] Набросок структуры компонента, можно просто в Paint.

### Главное меню
Например, логотип и кнопка авторизации / выхода, ник пользователя, если он авторизован.

- [x] Набросок структуры компонента.

### Меню взаимодействия с фотографией
Скачать, отредактировать комментарий, удалить.

- [x] Расположение?
> Например, появляется при наведении на фотографию или нажатию ПКМ.
- [x] Набросок структуры компонента.

### Фотография
- [x] Стиль?
> Например, закруглённые края, увеличивается наведении и т.п.
- [x] Где располагается комментарий?
- [x] Набросок структуры компонента.

### Редактирование фотографии
- [x] Модальное окно или отдельная страница? 
- [x] Какие элементы будут использоваться?
- [x] Набросок структуры компонента.

### Дополнительная информация
- [x] Будет ли футер и какую информацию он задержит?
> Например, кнопки с переходом на соц. сети разработчиков.
- [x] Набросок структуры компонента, если будет использоваться.

### Основная страница
Сложение всех элементов воедино. 

- [x] Где располагаются категории фотографий? ( все, мои )
- [x] Сколько фотографий на странице по стандарту?
- [x] Как новые фотографии добавляются на стрианцу?
> Например, при помощи кнопки или когда пользователь доскролил до конца.
- [x] Набросок структуры компонента.

**Comment by Noga-Ekaterina** [comment]
вот пример главной страницы. Цвета я просто наугад выбрал
<img width="1260" alt="Снимок экрана 2024-03-26 162645" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/6c55505e-1f7b-4b0b-a35d-afbe78747bfe">
а

**Comment by Noga-Ekaterina** [comment]
Главная страница
<img width="1260" alt="Снимок экрана 2024-03-26 162645" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/51cd1803-9902-42ce-869c-5f52eab1f2f8">

**Comment by Noga-Ekaterina** [comment]
- Задний фон:
![32b940a734eb4d9ea1a708b9add85153 1](https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/c00c0f99-a80f-490c-979b-693440ceb689)
- Акцентные цвета:
  - на светлом фоне: #C0B128.
  - на тёмном фоне: #FDFD3A.
- Цвет текста:
  - на светлом фоне: #000000.
  - на тёмном фоне: #FFFFFF.
-  Текст поверх акцентного цвета: #FFFFFF.

**Comment by Noga-Ekaterina** [comment]
- Шрифт:  lnter.
- Поля ввода:
  - с обводкой 1рх акцентного цвета. 
  - скругления 20рх. 
  - при фокусе обводка 2рх.
  
<img width="334" alt="Снимок экрана 2024-03-29 004048" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/bc0d6d5f-db54-4672-bbea-9f620333059c">

**Comment by Noga-Ekaterina** [comment]
Кнопки заполнены акцентным цветом, закругление 10рх.

**Comment by Noga-Ekaterina** [comment]
Регистрация и авторизация:
- будет будет через модальное окно.
- Элементы:
   - Ввод логина.
   - Ввод пароля. 
   - Кнопка авторизации. 
  
<img width="1260" alt="Снимок экрана 2024-03-29 191658" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/1915efa0-bf62-4878-b5e5-3659e90e1ea9">
<img width="1260" alt="Снимок экрана 2024-03-29 191540" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/c142d467-bbf6-4eed-ace8-153f3a96cb7e">

**Comment by Noga-Ekaterina** [comment]
Главное меню:
- Фон #180B0F.
- Вид до авторизации:

**Comment by Noga-Ekaterina** [comment]
Главное меню:
- Фон #180B0F.
- Вид до авторизации:
<img width="1132" alt="header" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/05687e76-e059-4055-93f0-c82c2c716042">
- Вид, когда пользователь авторизован:
<img width="1110" alt="Снимок экрана 2024-03-30 162809" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/f921a165-64ac-429e-a151-f1e5bbfb7552">
- Когда кликаешь на иконку, появляется окошко:

<img width="165" alt="Снимок экрана 2024-03-30 163221" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/04eadbc4-217e-4430-bdfa-7acf7d1d8e8a">

**Comment by Noga-Ekaterina** [comment]
Карточка с фото:
<img width="229" alt="Group 4" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/df0d7d6b-ecdb-4a31-89e6-95c6657adb6e">
Когда кликаешь на иконку "инфо", появляется дополнительная информация о фотографии, меню взаимодействия с фотографией и каточка становится такой:
<img width="264" alt="Снимок экрана 2024-03-29 225051" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/6ebfa4d4-d59a-49f5-b04f-6ac9b1f1ce1b">

**Comment by Noga-Ekaterina** [comment]
Редактирование фотографии:
- будет будет через модальное окно.
- Элементы:
  - Фотография, которую выбрали.
  - Поле для названия.
  - Поле для описания.
 
<img width="412" alt="Снимок экрана 2024-03-30 190155" src="https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/94f9d80e-a801-424e-a650-5fb83777461a">

**Comment by Noga-Ekaterina** [comment]
Основная страница
- Категории фотографий находятся в главном меню.
- По стандарту на странице 20 фотографий. 
- Новые фотографии добавляются, когда доскроллил до конца.
- Футера не будет.
![Desktop - 1](https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/e6808f5b-b256-4edf-b655-70ddd1b08ab1)
![Desktop - 7](https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/e8af22f4-b3bc-49b1-a34b-d5d97ad99989)

**Comment by Noga-Ekaterina** [comment]
Основная страница
- Категории фотографий находятся в главном меню.
- По стандарту на странице 20 фотографий. 
- Новые фотографии добавляются, когда доскроллил до конца.
- Футера не будет.
![Desktop - 1](https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/75ef137f-560b-44ff-b60d-1072edb2ab25)
![Desktop - 7](https://github.com/NyashStorage/coderock-2024-frontend/assets/122358946/b2ccef2b-462f-4717-a241-f92cbf5beeb5)

**Comment by Noga-Ekaterina** [comment]
Скролл-бар
- Задний фон: #4B4647.
- Фон ползунка: #C0B128.
- Закругление ползунка 50%.
